#!/bin/bash
. ./setenv
luarocks install lapis
luarocks install inspect
luarocks install lsqlite3
luarocks install bcrypt
luarocks install luautf8
luarocks install luacov
luarocks install luacov-reporter-lcov
luarocks install luasec
mkdir temp
mkdir storages
